Bump to 1.5.0
lagom/online-auction-java pull request #213
Opened 2019-04-17 17:29 UTC by ignasi35

Supersedes #212

2019-04-17 17:29 UTC, lightbend-cla-validator commented
Hi @RustemZ,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2019-04-17 19:38 UTC, ignasi35 commented
Services using Akka's `ServiceDiscovery` don't declare a `method`. This needs fixing before merging.

2019-04-17 19:38 UTC, ignasi35 commented
related https://github.com/lagom/online-auction-scala/pull/118#issuecomment-484231933

2019-04-17 22:06 UTC, marcospereira submitted a review, later dismissed
LGTM.

Should ` akka.discovery.method = akka-dns` be a default in `lagom-akka-discovery-service-locator`?

2019-04-17 22:08 UTC, marcospereira reviewed
Notice a small detail regarding the dependency.

2019-04-17 22:08 UTC, marcospereira commented on build.sbt
> +val akkaDiscoveryServiceLocator = "com.lightbend.lagom" %% "lagom-scaladsl-akka-discovery-service-locator" % "1.0.0"
Hum, on a second pass: use javadsl instead.

2019-04-17 23:50 UTC, TimMoore requested changes
This seems to be incomplete. My guess is that deployment on Kubernetes hasn't been tested, because I don't think it will work as is. `README.md` and `KUBERNETES.md` still refer to Lightbend Orchestration.

If you want to split the work into separate pull requests to update for development and deployment, I think that's OK, but in that case, take out all of the deployment stuff entirely until that part is done. Otherwise it's actively misleading and people could waste a lot of time trying to figure out something that isn't expected to work.

2019-04-17 23:50 UTC, TimMoore commented on bidding-impl/src/main/resources/application.conf
> +akka.discovery.method = akka-dns
Doesn't it need other configuration for Cluster Bootstrap? Should production configuration be split into another file like `prod-application.conf`?

2019-04-17 23:54 UTC, TimMoore commented
> Should `akka.discovery.method = akka-dns` be a default in `lagom-akka-discovery-service-locator`?

If it's going to set a default (I have requested that it should since the beginning) the best default to use would be [aggregate](https://doc.akka.io/docs/akka/current/discovery/#discovery-method-aggregate-multiple-discovery-methods) preconfigured with both [config](https://doc.akka.io/docs/akka/current/discovery/#discovery-method-configuration) and [DNS](https://doc.akka.io/docs/akka/current/discovery/#discovery-method-dns) (in that order of priority). That makes it really easy to plug in manual configuration to override DNS entries or add ones that aren't available in DNS.

2019-04-24 20:14 UTC, closed without merging

2019-04-24 20:16 UTC, ignasi35 commented
@TimMoore I've raised https://github.com/lagom/lagom-akka-discovery-service-locator/issues/81 to track that.